---
name: TVHeadend
version: 1.0.5
stage: experimental
slug: tvheadend
description: TV streaming server and recorder.
url: "https://github.com/reviloledieps/hassio-addons"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
webui: "http://[HOST]:[PORT:9981]/"
devices:
  - /dev/dvb
  - /dev/dri
host_network: true
map:
  - "config:rw"
options:
  system_packages: []
  init_commands: []
schema:
  system_packages:
    - str
  init_commands:
    - str